version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
     - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    command: python3 run.py runserver

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "8000:8000"
    command: python3 -m http.server

