version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
     - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    links:
      - postgres
    environment:
      FLASK_APP: "app/__init__.py"
    working_dir: /usr/src/app
    command: python3 run.py runserver

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "8000:8000"
    links:
      - backend
    command: python3 -m http.server

  postgres:
    image: postgres:10.1
    volumes:
      - pg:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: dyplom

volumes:
  pg: