"""empty message

Revision ID: ded8e7e21cfa
Revises: 
Create Date: 2018-01-04 17:23:15.210275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded8e7e21cfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vk_app',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=True),
    sa.Column('expire', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('app_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vk_app')
    # ### end Alembic commands ###
